apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "release-server.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "release-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    storage_path: {{ .Values.persistence.path }}
    max_packages: {{ .Values.app.maxPackages }}
    port: {{ .Values.app.port }}
