{{- if .Values.app.authToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release-server.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "release-server.labels" . | nindent 4 }}
type: Opaque
data:
  auth-token: {{ .Values.app.authToken | b64enc | quote }}
{{- end }}
